### ISSUE TITLE
Different ouput in the exercise 12

### ISSUE THREAD

**Issue by AVI18794** [TrainingByPackt/Introduction-to-Natural-Language-Processing#1]
While I am trying to execute the commands in the activity 12 the output I am getting is different from what is mentioned in the book and the ipynb file.Here is the screenshot attached to the code.
![image](https://user-images.githubusercontent.com/37730987/69212070-34f1b380-0b86-11ea-8ccd-d8b30078cdc2.png)

**Comment by AVI18794** [comment]
After modifying the regex to re.sub(r'([^\s\w])+')  it removes all the # and @ symbols but the underscore is still there.
![image](https://user-images.githubusercontent.com/37730987/69213024-f1e50f80-0b88-11ea-9f74-a024e3260cd5.png)
@dgunning  please have a look.

**Comment by sohomghosh** [comment]
@AVI18794 
Please ensure you are using re version 2.2.1and Python 3. The above code works fine for these versions. I have verified it.

**Comment by AVI18794** [comment]
@sohomghosh Isn't the re inbuilt module of python? Why do we need to install it seperately? If I am not wrong then its re2 and I used the inbuilt re module of python.

**Comment by AVI18794** [comment]
I checked the version of re as well and the result is 
![image](https://user-images.githubusercontent.com/37730987/69302879-1270a080-0c41-11ea-9ff6-c4c420641fa5.png) @sohomghosh

**Comment by sohomghosh** [comment]
Can you please share the output of the following?

import re
re.__version__

**Comment by AVI18794** [comment]
@sohomghosh  I have already uploaded the image of the following command for version checking.Check this link.
https://github.com/TrainingByPackt/Natural-Language-Processing-Fundamentals/issues/1#issuecomment-556909107

**Comment by sohomghosh** [comment]
@AVI18794
I executed it on google collab it worked fine. Please refer to this collab notebook [[link](https://colab.research.google.com/drive/140XM5ew75bpQGenZC7iYpOhgWXUY7qDN)].

![image](https://user-images.githubusercontent.com/7260463/69356616-c0b03080-0ca9-11ea-83aa-e88347b8bd38.png)

**Comment by AVI18794** [comment]
Strange! It's not working in my laptop but working fine in the google colab, might be I am missing something.

**Comment by AVI18794** [comment]
I am closing this as it seems working fine. Thanks @sohomghosh
