### ISSUE TITLE
Lesson 2: Figures are inter changed.

### ISSUE THREAD

**Issue by hardikkamboj** [TrainingByPackt/Introduction-to-Natural-Language-Processing#2]
In the Types of Data section, in lesson 2, the two figures for categorizing Data base on Structure and Categorizing Data based on content are misplaced.

**Comment by sohomghosh** [comment]
> In the Types of Data section, in lesson 2, the two figures for categorizing Data base on Structure and Categorizing Data based on content are misplaced. 

You are right. Thanks for pointing this out. This has been taken care in the latest edition.
